### ISSUE TITLE
Samsung S7/Android 8.0 pictures taking doesn't work

### ISSUE THREAD

**Issue by blackboxembedded** [blackboxembedded/WunderLINQ-Android#184]
Samsung S7/Android 8.0 pictures taking doesn't work.

The user-submitted log shows it couldn't create the directory that it places the photos in.

PhotoService: Unable to create directory: /storage/emulated/0/DCIM/WunderLINQ
09-24 21:17:14.850  5197  5197 D PhotoService: Error Saving: 
09-24 21:17:14.850  5197  5197 W System.err: java.io.FileNotFoundException: /storage/emulated/0/DCIM/WunderLINQ/IMG_20240924_211714.jpg (No such file or directory)
09-24 21:17:14.850  5197  5197 W System.err: 	at java.io.FileOutputStream.open0(Native Method)
09-24 21:17:14.850  5197  5197 W System.err: 	at java.io.FileOutputStream.open(FileOutputStream.java:287)
09-24 21:17:14.850  5197  5197 W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
09-24 21:17:14.850  5197  5197 W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
09-24 21:17:14.851  5197  5197 W System.err: 	at com.blackboxembedded.WunderLINQ.PhotoService$1.onCaptureSuccess(PhotoService.java:186)
09-24 21:17:14.851  5197  5197 W System.err: 	at androidx.camera.core.ImageCapture$ImageCaptureRequest.lambda$dispatchImage$0$androidx-camera-core-ImageCapture$ImageCaptureRequest(ImageCapture.java:2640)
09-24 21:17:14.851  5197  5197 W System.err: 	at androidx.camera.core.ImageCapture$ImageCaptureRequest$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
09-24 21:17:14.851  5197  5197 W System.err: 	at android.os.Handler.handleCallback(Handler.java:789)
09-24 21:17:14.851  5197  5197 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-24 21:17:14.851  5197  5197 W System.err: 	at android.os.Looper.loop(Looper.java:164)
09-24 21:17:14.851  5197  5197 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
09-24 21:17:14.851  5197  5197 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-24 21:17:14.851  5197  5197 W System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
09-24 21:17:14.851  5197  5197 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by blackboxembedded** [comment]
This might be fixed with a recent change in the mainifest, but the app doesn't technically support Android 8.0
